[package]
name = "runner"
version = "0.1.0"
edition = "2024"

[dependencies]
dialoguer = "0.11"
console = "0.15"
anyhow = "1.0"
clap = { version = "4.5.57", features = ["derive"] }
regex = "1.10.5"
libc = "0.2"
